### ISSUE TITLE
Unreliable online usage

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12mon#41] opened 2023-03-08 00:40 UTC
The Hall B logbooks keep suggesting, again and again, year after year, that they have to restart mon12 to get it to work right, in the sense of creating/displaying histograms in mon12 that really reflect the data that's being recorded.  That seems to be isolated to occupancies in certain detectors, probably DC and BMT.  Would be really good to figure out why and fix it.  If it's really beam-related, then selecting on high-purity trigger bits should have already done the job, but that's already been done long ago.  Maybe something else is going on.  Very strange ...

**Comment by raffaelladevita** [comment] 2023-03-08 17:55
I have been investigating the issue but haven't found yet a way to reproduce it or work around it. 

Just for the record, the main symptoms are:
- the DC occupancies show a sector dependence, with maximum occupancy in sector 1 and minimum in sector 6;
-  the DC multiplicities show a peak at 0 which is increasing with the sector number, relative to the events with multiplicity larger than 0;
- the helicity signals show an abnormal population for both helicity, sync, and quartet.

Based on that and what was reported by shift takers:
- the problem is due to mon12 itself because it is always fixed by restarting it; 
- no errors are reported, most likely due to https://github.com/JeffersonLab/clas12-offline-software/issues/899, which makes it difficult to identify; 
- since hits are ordered by sector, the decreasing DC occupancy could be due to the events being sort of truncated or corrupted since the higher-number sectors would be more affected; 
- the helicity anomaly is not understood at all. Helicity signals are read via fADCs and there is no apparent reason why those should be affected more than others;
- the issue may arise due to problems with the ET connection, evio-hipo decoding or misbehavior of mon12 hipo event processing. I have been trying to verify the latter since that should be reproducible also when running from file. I have been implementing a bit more diagnostic to help identify the cause.

**Comment by baltzell** [comment] 2023-03-12 20:58
Next COATJAVA version supports setting verbosity.

**Closed as completed** 2023-03-16 22:43 UTC
